### ISSUE TITLE
Problem Statement

### ISSUE THREAD

**Issue by enkiluv** [hy57in/2021-Industry-Hands-On-Project#1]
Requirements Gathering과 함께 이 시스템/서비스가 해결하고자 하는 <B>비즈니스 관점에서의 Problem Statement</B>가 있어야 합니다. README 문서에 간략히 Problem Statement를 추가하기 바랍니다.

**Comment by chaehuiseon** [comment]
problem statement에 대하여
https://github.com/hy57in/2021-Industry-Hands-On-Project/blob/main/README.md 에 추가하였습니다. 감사합니다.
